apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-server
  labels:
    app: fortio-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-server
  template:
    metadata:
      labels:
        app: fortio-server
    spec:
      containers:
      - name: fortio-server
        # image: fortio/fortio:latest
        image: public.ecr.aws/v6x6b8s5/fortio:1.16.0
        ports:
        - containerPort: 8080
        - containerPort: 8079
---
apiVersion: v1
kind: Service
metadata:
  name: fortio-server-service
spec:
  selector:
    app: fortio-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
    - protocol: TCP
      port: 8079
      targetPort: 8079
      name: internal
  type: NodePort
